language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements-test.txt
  - pip install coverage
  - pip install coveralls
# command to run tests
script:
  coverage run runtests
after_success:
  coveralls
